spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  topic:
    topic-technocrat
    
spring:
  kafka:
    groupId: technocrat

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.memorynotfound: DEBUG